# Build Stage
FROM node:20-slim AS builder

WORKDIR /app
COPY . .

RUN npm ci
RUN npm run build

# Final Stage
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
